<%@ Page Title="" Language="C#" MasterPageFile="~/Admin2.Master" AutoEventWireup="true" CodeBehind="AAvailable.aspx.cs" Inherits="RailwayReservationPart1.AAvailable" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
        &nbsp;</p>
    <p>
        <asp:Label ID="Label1" runat="server" ForeColor="Black" Text="Train Number:"></asp:Label>
        &nbsp;
        <asp:TextBox ID="TextBox1" runat="server" TextMode="Number" ReadOnly="True"></asp:TextBox>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Label ID="Label5" runat="server" Text="Train Name:"></asp:Label>
&nbsp;
        <asp:TextBox ID="TextBox4" runat="server" ReadOnly="True"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button2" runat="server" Text="Insert Class and Seats" Visible="False" OnClick="Button2_Click" />
    </p>
    <p>
        <asp:Label ID="Label3" runat="server" Text="Type:" Visible="False"></asp:Label>
&nbsp;
        <asp:DropDownList ID="DropDownList1" runat="server" Height="16px" Visible="False" Width="110px">
            <asp:ListItem Selected="True">-----</asp:ListItem>
            <asp:ListItem>Sleeper</asp:ListItem>
            <asp:ListItem>First AC</asp:ListItem>
            <asp:ListItem>Second AC</asp:ListItem>
            <asp:ListItem>Third AC</asp:ListItem>
        </asp:DropDownList>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Label ID="Label4" runat="server" Text="Total Seats:" Visible="False"></asp:Label>
&nbsp;
        <asp:TextBox ID="TextBox3" runat="server" TextMode="Number" Visible="False"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Update Table" Visible="False"/>
    </p>
    <p>
        <asp:Label ID="Label6" runat="server" ForeColor="Red"></asp:Label>
    </p>
    <p>
        <asp:Label ID="Label2" runat="server" ForeColor="Black" Text="Train Class and Total Seats:"></asp:Label>
    </p>
    <p>
        <asp:GridView ID="GridView1" runat="server" CellPadding="4" ForeColor="#333333" AutoGenerateColumns="False" OnRowDeleted="GridView1_RowDeleted" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" DataSourceID="SqlDataSource1" DataKeyNames="Type" Width="1177px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="Type" HeaderText="Type" SortExpression="Type" ReadOnly="true"/>
                <asp:BoundField DataField="Seats_Available" HeaderText="Seats Available" SortExpression="Seats_Available" />
            </Columns>
            <EditRowStyle BorderColor="Black" BorderStyle="None" />
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Seat_Availability] WHERE ([Train_ID] = @Train_ID)" UpdateCommand="UPDATE Seat_Availability SET Seats_Available=@Seats_Available WHERE Type=@Type" DeleteCommand="DELETE FROM Seat_Availability WHERE Type=@Type">
            <SelectParameters>
                <asp:ControlParameter ControlID="TextBox1" Name="Train_ID" PropertyName="Text" Type="Decimal" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="Type" Type="String" />
                <asp:Parameter Name="Seats_Available" Type="Int32" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="Type" Type="String" />
            </DeleteParameters>
        </asp:SqlDataSource>
    </p>
    <p>
        &nbsp;</p>
    <p>
        <asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Back To Train Details" />
    </p>
    </asp:Content>
