<%@ Page Title="" Language="C#" MasterPageFile="~/Admin2.Master" AutoEventWireup="true" CodeBehind="ATrain.aspx.cs" Inherits="RailwayReservationPart1.ViewTrain" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">   
    
    <br />
    
    <span style="color: #000000">    
    Insert Train Details:<br />
    <br />
    Train Number:&nbsp; <asp:TextBox ID="TextBox1" runat="server" TextMode="Number" MaxLength="5"></asp:TextBox>
&nbsp; Train_Name:&nbsp; <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Insert" Width="80px" />
    <br />
    <br />
    <br />
    <asp:Label ID="Label1" runat="server" ForeColor="Red"></asp:Label>
    <br />
    <br />
    TRAIN DETAILS:<br />
    <br />
    </span>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Train_num" DataSourceID="SqlDataSource1" AllowSorting="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="#333333" style="color: #000000" Height="187px" Width="1175px" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowDataBound="GridView1_RowDataBound">
        <AlternatingRowStyle BackColor="White" />
    <Columns>
        <asp:BoundField DataField="Train_num" HeaderText="Train Number" ReadOnly="True" SortExpression="Train_num" />
        <asp:BoundField DataField="Train_Name" HeaderText="Train Name" SortExpression="Train_Name" />
    </Columns>
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" BorderColor="Black" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM Train_Details" UpdateCommand="UPDATE [Train_Details] SET [Train_Name]=@Train_Name where [Train_num]=@Train_num" DeleteCommand="DELETE from [Train_Details] where [Train_num]=@Train_num"></asp:SqlDataSource>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Button ID="Button4" runat="server" Height="31px" OnClick="Button4_Click" Text="Days Running" Width="159px" />
    &nbsp;&nbsp;
    <asp:Button ID="Button2" runat="server" Height="31px" OnClick="Button2_Click" Text="Route" Width="159px" />
&nbsp;
    <asp:Button ID="Button3" runat="server" Height="31px" OnClick="Button3_Click" Text="Availability" Width="159px" />
    &nbsp;&nbsp;&nbsp;
    <asp:Label ID="Label2" runat="server" ForeColor="Red"></asp:Label>
    <br />
        <br />
</asp:Content>

